-- Procedimientos almacenados de AUTO

-- SELECT 

DROP PROCEDURE IF EXISTS SELECCIONAR_AUTO 
GO

CREATE PROCEDURE  SELECCIONAR_AUTO @NUMPLACA NCHAR(6)
AS 
BEGIN 
	SELECT NUMPLACA, MARCA, ID_DISTRIBUIDOR, TIPO_MOTOR, TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER FROM dbo.[AUTO]
	WHERE NUMPLACA = @NUMPLACA
END
GO

-- INSERT

DROP PROCEDURE IF EXISTS INSERTAR_AUTO
GO

CREATE PROCEDURE INSERTAR_AUTO @NUMPLACA NCHAR(6), @MARCA NCHAR(100), @DISTRIBUIDOR INT, 
	@TIPO_MOTOR NCHAR(100), @TIPO_VEHICULO NCHAR(100), @AUTO_ANIO INT, @PRECIO_ALQUILER DECIMAL(6,2)
AS
BEGIN
	INSERT INTO dbo.[AUTO](NUMPLACA, MARCA, ID_DISTRIBUIDOR , TIPO_MOTOR, 
	TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER)
	VALUES (@NUMPLACA, @MARCA, @DISTRIBUIDOR , @TIPO_MOTOR, 
	@TIPO_VEHICULO, @AUTO_ANIO, @PRECIO_ALQUILER)
END
GO

-- UPDATE 

DROP PROCEDURE IF EXISTS ACTUALIZAR_AUTO
GO 

CREATE PROCEDURE ACTUALIZAR_AUTO @NUMPLACA NCHAR(6), @MARCA NCHAR(100), @DISTRIBUIDOR INT,
	@TIPO_MOTOR NCHAR(100), @TIPO_VEHICULO NCHAR(10), @AUTO_ANIO INT, @PRECIO_ALQUILER DECIMAL(6,2)
AS 
BEGIN
	IF @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL AND @AUTO_ANIO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET MARCA = @MARCA
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL AND @AUTO_ANIO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET ID_DISTRIBUIDOR = @DISTRIBUIDOR
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_VEHICULO IS NULL AND @AUTO_ANIO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET TIPO_MOTOR = @TIPO_MOTOR
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @AUTO_ANIO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET TIPO_VEHICULO = @TIPO_VEHICULO
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET AUTO_ANIO = @AUTO_ANIO
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL
	AND @AUTO_ANIO IS NULL
		UPDATE dbo.[AUTO]
		SET PRECIO_ALQUILER = @PRECIO_ALQUILER
		WHERE NUMPLACA = @NUMPLACA
	ELSE 
		UPDATE dbo.[AUTO]
		SET MARCA = @MARCA, ID_DISTRIBUIDOR = @DISTRIBUIDOR, TIPO_MOTOR = @TIPO_MOTOR, 
		TIPO_VEHICULO = @TIPO_VEHICULO, AUTO_ANIO = @AUTO_ANIO,PRECIO_ALQUILER = @PRECIO_ALQUILER
		WHERE NUMPLACA = @NUMPLACA
END
GO

-- DELETE 

DROP PROCEDURE IF EXISTS ELIMINAR_AUTO
GO 

CREATE PROCEDURE ELIMINAR_AUTO @NUMPLACA NCHAR(6)
AS 
BEGIN 
	DELETE FROM dbo.[AUTO]
	WHERE NUMPLACA = @NUMPLACA
END
