CREATE DATABASE ALQUILER_AUTOS;

USE ALQUILER_AUTOS;

CREATE TABLE DISTRIBUIDOR (
	ID INT PRIMARY KEY,
	NOMBRE NCHAR(100) NOT NULL,
	DIRECCION NCHAR(250),
	CIUDAD NCHAR(100),
	TELEFONO NCHAR(20) UNIQUE,
	EMAIL NCHAR(250) UNIQUE
)

CREATE TABLE AUTO (
	NUMPLACA NCHAR(6) PRIMARY KEY,
	MARCA NCHAR(100),
	DISTRIBUIDOR INT FOREIGN KEY REFERENCES DISTRIBUIDOR(ID),
	TIPO_MOTOR NCHAR(100), 
	TIPO_VEHICULO NCHAR(100),
	CAR_YEAR INT,
	PRECIO_ALQUILER DECIMAL(3,2)
)

CREATE TABLE CLIENTE(
	CEDULA NCHAR(12) PRIMARY KEY,
	NOMBRE NCHAR(100) NOT NULL,
	APELLIDO NCHAR(100) NOT NULL,
	DIRECCION NCHAR(250) NOT NULL,
	TELEFONO NCHAR(20) UNIQUE NOT NULL,
	EMAIL NCHAR(250) UNIQUE,
	LICENCIA NCHAR(20) UNIQUE NOT NULL
)

CREATE TABLE ALQUILER (
	MATRICULA NCHAR(6),
	CEDULA_CLIENTE NCHAR(12),
	FECHA_SAlIDA DATE NOT NULL,
	FECHA_ENTRADA DATE NOT NULL,
	FOREIGN KEY (MATRICULA) REFERENCES AUTO(NUMPLACA),
	FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE(CEDULA),
	PRIMARY KEY (MATRICULA, CEDULA_CLIENTE)
)

-- Procedimientos almacenados de DISTRIBUIDOR

-- SELECT

DROP PROCEDURE IF EXISTS SELECCIONAR_DISTRIBUIDOR
GO 

CREATE PROCEDURE SELECCIONAR_DISTRIBUIDOR @ID INT
AS 
BEGIN 
	SELECT * FROM dbo.[DISTRIBUIDOR]
	WHERE ID = @ID
END 
GO

-- INSERT 

DROP PROCEDURE IF EXISTS INSERTAR_DISTRINUIDOR 
GO 

CREATE PROCEDURE INSERTAR_DISTRINUIDOR @ID INT, @NOMBRE NCHAR(100), @DIRECCION NCHAR(250),
	@CIUDAD NCHAR(100), @TELEFONO NCHAR(25), @EMAIL NCHAR(250) 
AS
BEGIN 
	INSERT INTO dbo.[DISTRIBUIDOR] (ID,NOMBRE, DIRECCION, CIUDAD, TELEFONO, EMAIL)
	VALUES (@ID,@NOMBRE,@DIRECCION,@CIUDAD,@TELEFONO,@EMAIL)
END
GO

-- UPDATE 

DROP PROCEDURE IF EXISTS ACTUALIZAR_DISTRIBUIDOR
GO 

CREATE PROCEDURE ACTUALIZAR_DISTRIBUIDOR @ID INT, @NOMBRE NCHAR(100), @DIRECCION NCHAR(250),
	@CIUDAD NCHAR(100), @TELEFONO NCHAR(25), @EMAIL NCHAR(250)
AS 
BEGIN
	IF @CIUDAD IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET DIRECCION = @DIRECCION
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET CIUDAD = @CIUDAD
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @CIUDAD IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET TELEFONO = @TELEFONO
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @CIUDAD IS NULL AND @TELEFONO IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET EMAIL = @EMAIL
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @CIUDAD IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET NOMBRE = @NOMBRE
		WHERE ID = @ID
	ELSE 
		UPDATE dbo.[DISTRIBUIDOR]
		SET NOMBRE = @NOMBRE, DIRECCION = @DIRECCION, 
		CIUDAD = @CIUDAD, TELEFONO = @TELEFONO,EMAIL = @EMAIL
		WHERE ID = @ID
END
GO

-- DELETE 

DROP PROCEDURE IF EXISTS ELIMINAR_DISTRIBUIDOR 
GO

CREATE PROCEDURE ELIMINAR_DISTRIBUIDOR @ID INT
AS
BEGIN
	DELETE FROM dbo.[DISTRIBUIDOR]
	WHERE ID = @ID
END
GO

-- Procedimientos almacenados de AUTO

-- SELECT 

DROP PROCEDURE IF EXISTS SELECCIONAR_AUTO 
GO

CREATE PROCEDURE  SELECCIONAR_AUTO @NUMPLACA NCHAR(6)
AS 
BEGIN 
	SELECT * FROM dbo.[AUTO]
	WHERE NUMPLACA = @NUMPLACA
END
GO

-- INSERT

DROP PROCEDURE IF EXISTS INSERTAR_AUTO
GO

CREATE PROCEDURE INSERTAR_AUTO @NUMPLACA NCHAR(6), @MARCA NCHAR(100), @DISTRIBUIDOR INT, 
	@TIPO_MOTOR NCHAR(100), @TIPO_VEHICULO NCHAR(100), @CAR_YEAR INT, @PRECIO_ALQUILER DECIMAL(3,2)
AS
BEGIN
	INSERT INTO dbo.[AUTO](NUMPLACA, MARCA, DISTRIBUIDOR , TIPO_MOTOR, 
	TIPO_VEHICULO, CAR_YEAR, PRECIO_ALQUILER)
	VALUES (@NUMPLACA, @MARCA, @DISTRIBUIDOR , @TIPO_MOTOR, 
	@TIPO_VEHICULO, @CAR_YEAR, @PRECIO_ALQUILER)
END
GO

-- UPDATE 

DROP PROCEDURE IF EXISTS ACTUALIZAR_AUTO
GO 

CREATE PROCEDURE ACTUALIZAR_AUTO @NUMPLACA NCHAR(6), @MARCA NCHAR(100), @DISTRIBUIDOR INT,
	@TIPO_MOTOR NCHAR(100), @TIPO_VEHICULO NCHAR(10), @CAR_YEAR INT, @PRECIO_ALQUILER DECIMAL(3,2)
AS 
BEGIN
	IF @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL AND @CAR_YEAR IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET MARCA = @MARCA
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL AND @CAR_YEAR IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET DISTRIBUIDOR = @DISTRIBUIDOR
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_VEHICULO IS NULL AND @CAR_YEAR IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET TIPO_MOTOR = @TIPO_MOTOR
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @CAR_YEAR IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET TIPO_VEHICULO = @TIPO_VEHICULO
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET CAR_YEAR = @CAR_YEAR
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL
	AND @CAR_YEAR IS NULL
		UPDATE dbo.[AUTO]
		SET PRECIO_ALQUILER = @PRECIO_ALQUILER
		WHERE NUMPLACA = @NUMPLACA
	ELSE 
		UPDATE dbo.[AUTO]
		SET MARCA = @MARCA, DISTRIBUIDOR = @DISTRIBUIDOR, TIPO_MOTOR = @TIPO_MOTOR, 
		TIPO_VEHICULO = @TIPO_VEHICULO, CAR_YEAR = @CAR_YEAR,PRECIO_ALQUILER = @PRECIO_ALQUILER
		WHERE NUMPLACA = @NUMPLACA
END
GO

-- DELETE 

DROP PROCEDURE IF EXISTS ELIMINAR_AUTO
GO 

CREATE PROCEDURE ELIMINAR_AUTO @NUMPLACA NCHAR(6)
AS 
BEGIN 
	DELETE FROM dbo.[AUTO]
	WHERE NUMPLACA = @NUMPLACA
END

-- Procedimientos de CLIENTE

-- SELECT 

DROP PROCEDURE IF EXISTS SELECCIONAR_CLIENTE
GO

CREATE PROCEDURE SELECCIONAR_CLIENTE @CEDULA NCHAR(12)
AS
BEGIN
	SELECT * FROM dbo.[CLIENTE]
	WHERE CEDULA = @CEDULA
END

-- INSERT 

DROP PROCEDURE IF EXISTS INSERTAR_CLIENTE
GO

CREATE PROCEDURE INSERTAR_CLIENTE @CEDULA NCHAR(12), @NOMBRE NCHAR(100), @APELLIDO NCHAR(100),
	@DIRECCION NCHAR(250), @TELEFONO NCHAR(20), @EMAIL NCHAR(250), @LICENCIA NCHAR(20)
AS 
BEGIN
	INSERT INTO dbo.[CLIENTE](CEDULA, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, LICENCIA)
	VALUES(@CEDULA, @NOMBRE, @APELLIDO, @DIRECCION, @TELEFONO, @EMAIL, @LICENCIA)
END

-- UPDATE

DROP PROCEDURE IF EXISTS ACTUALIZAR_CLIENTE
GO

CREATE PROCEDURE ACTUALIZAR_CLIENTE @CEDULA NCHAR(12), @NOMBRE NCHAR(100), @APELLIDO NCHAR(100),
	@DIRECCION NCHAR(250), @TELEFONO NCHAR(20), @EMAIL NCHAR(250), @LICENCIA NCHAR(20)
AS 
BEGIN 
	IF @APELLIDO IS NULL AND @DIRECCION IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL AND 
	@LICENCIA IS NULL
	UPDATE dbo.[CLIENTE]
	SET NOMBRE = @NOMBRE
	WHERE CEDULA = @CEDULA
	ELSE IF @NOMBRE IS NULL AND @DIRECCION IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL AND 
	@LICENCIA IS NULL
	UPDATE dbo.[CLIENTE]
	SET APELLIDO = @APELLIDO
	WHERE CEDULA = @CEDULA
	ELSE IF @NOMBRE IS NULL AND @APELLIDO IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL AND 
	@LICENCIA IS NULL
	UPDATE dbo.[CLIENTE]
	SET DIRECCION = @DIRECCION
	WHERE CEDULA = @CEDULA
	ELSE IF @NOMBRE IS NULL AND @APELLIDO IS NULL AND @DIRECCION IS NULL AND @EMAIL IS NULL AND 
	@LICENCIA IS NULL
	UPDATE dbo.[CLIENTE]
	SET TELEFONO = @TELEFONO
	WHERE CEDULA = @CEDULA
	ELSE IF @NOMBRE IS NULL AND @APELLIDO IS NULL AND @DIRECCION IS NULL AND @TELEFONO IS NULL AND 
	@LICENCIA IS NULL
	UPDATE dbo.[CLIENTE]
	SET EMAIL = @EMAIL
	WHERE CEDULA = @CEDULA
	ELSE IF @NOMBRE IS NULL AND @APELLIDO IS NULL AND @DIRECCION IS NULL AND @TELEFONO IS NULL AND 
	@EMAIL IS NULL
	UPDATE dbo.[CLIENTE]
	SET LICENCIA = @LICENCIA
	WHERE CEDULA = @CEDULA
	ELSE
	UPDATE dbo.[CLIENTE]
	SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, DIRECCION = @DIRECCION, TELEFONO = @TELEFONO,
	EMAIL = @EMAIL, LICENCIA = @LICENCIA
	WHERE CEDULA = @CEDULA
END

-- DELETE 
DROP PROCEDURE IF EXISTS ELIMINAR_CLIENTE
GO

CREATE PROCEDURE ELIMINAR_CLIENTE @CEDULA NCHAR(12)
AS 
BEGIN
	DELETE FROM CLIENTE
	WHERE CEDULA = @CEDULA
END
GO

-- Procedimientos almacenados de ALQUILER

-- SELECT 
DROP PROCEDURE IF EXISTS SELECCIONAR_ALQUILER
GO

CREATE PROCEDURE SELECCIONAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12)
AS 
BEGIN
	IF @MATRICULA IS NOT NULL AND @CEDULA_CLIENTE IS NOT NULL
	SELECT * FROM dbo.[ALQUILER]
	WHERE MATRICULA = @MATRICULA AND CEDULA_CLIENTE = @CEDULA_CLIENTE
	ELSE IF @MATRICULA IS NULL
	SELECT * FROM dbo.[ALQUILER]
	WHERE CEDULA_CLIENTE = @CEDULA_CLIENTE
	ELSE
	SELECT * FROM dbo.ALQUILER
	WHERE MATRICULA = @MATRICULA
END

-- INSERT

DROP PROCEDURE IF EXISTS INSERTAR_ALQUILER
GO

CREATE PROCEDURE INSERTAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12), @FECHA_SALIDA DATE,
	@FECHA_ENTRADA DATE
AS 
BEGIN 
	INSERT INTO dbo.[ALQUILER](MATRICULA,CEDULA_CLIENTE,FECHA_SAlIDA,FECHA_ENTRADA)
	VALUES(@MATRICULA,@CEDULA_CLIENTE,@FECHA_SALIDA,@FECHA_ENTRADA)
END

-- UPDATE

DROP PROCEDURE IF EXISTS ACTUALIZAR_ALQUILER
GO

CREATE PROCEDURE ACTUALIZAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12), @FECHA_SALIDA DATE,
	@FECHA_ENTRADA DATE, @OPCION INT
AS 
BEGIN
	IF @FECHA_ENTRADA IS NULL
	UPDATE dbo.[ALQUILER]
	SET FECHA_SAlIDA = @FECHA_SAlIDA
	WHERE CEDULA_CLIENTE = @CEDULA_CLIENTE AND MATRICULA = @MATRICULA
	ELSE 
	UPDATE dbo.[ALQUILER]
	SET FECHA_ENTRADA = @FECHA_ENTRADA
	WHERE CEDULA_CLIENTE = @CEDULA_CLIENTE AND MATRICULA = @MATRICULA
END

-- DELETE 

DROP PROCEDURE IF EXISTS ELIMINAR_ALQUILER
GO

CREATE PROCEDURE ELIMINAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12)
AS
BEGIN
	DELETE FROM dbo.ALQUILER
	WHERE MATRICULA = @MATRICULA AND CEDULA_CLIENTE = @CEDULA_CLIENTE
END
GO

-- TRIGGERS

-- Tablas de Bitacora

USE ALQUILER_AUTOS

CREATE TABLE ALQUILER_BIT (
	MATRICULA NCHAR(6),
	CEDULA_CLIENTE NCHAR(12),

	EXE_USER VARCHAR(50),
	EXE_MAQUINA VARCHAR(50),
	EXE_DATE DATETIME,
	EXE_ACCION VARCHAR(2)
)

CREATE TABLE AUTO_BIT (
	NUMPLACA NCHAR(6),

	EXE_USER VARCHAR(50),
	EXE_MAQUINA VARCHAR(50),
	EXE_DATE DATETIME,
	EXE_ACCION VARCHAR(2)
)

CREATE TABLE CLIENTE_BIT (
	CEDULA NCHAR(6),

	EXE_USER VARCHAR(50),
	EXE_MAQUINA VARCHAR(50),
	EXE_DATE DATETIME,
	EXE_ACCION VARCHAR(2)
)

CREATE TABLE DISTRIBUIDOR_BIT (
	ID INT,

	EXE_USER VARCHAR(50),
	EXE_MAQUINA VARCHAR(50),
	EXE_DATE DATETIME,
	EXE_ACCION VARCHAR(2)
)

-- TRIGGERS PARA LA BITACORA ALQUILER

-- TRIGGER INSERT

DROP TRIGGER IF EXISTS TRG_ALQUILER_I
GO

CREATE TRIGGER TRG_ALQUILER_I
	ON dbo.[ALQUILER]
	AFTER INSERT
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[ALQUILER_BIT](MATRICULA, CEDULA_CLIENTE, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT MATRICULA, CEDULA_CLIENTE,SUSER_NAME(), HOST_NAME(), GETDATE(), 'I'
	FROM INSERTED
END
GO

-- TRIGGER DELETE
DROP TRIGGER IF EXISTS TRG_ALQUILER_D
GO

CREATE TRIGGER TRG_ALQUILER_D
	ON dbo.[ALQUILER]
	AFTER DELETE
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[ALQUILER_BIT](MATRICULA, CEDULA_CLIENTE, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT MATRICULA, CEDULA_CLIENTE,SUSER_NAME(), HOST_NAME(), GETDATE(), 'D'
	FROM DELETED
END
GO

-- TRIGGER UPDATE

DROP TRIGGER IF EXISTS TRG_ALQUILER_D
GO

CREATE TRIGGER TRG_ALQUILER_U
	ON dbo.[ALQUILER]
	AFTER UPDATE
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[ALQUILER_BIT](MATRICULA, CEDULA_CLIENTE, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT MATRICULA, CEDULA_CLIENTE,SUSER_NAME(), HOST_NAME(), GETDATE(), 'UI'
	FROM INSERTED

	INSERT INTO dbo.[ALQUILER_BIT](MATRICULA, CEDULA_CLIENTE, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT MATRICULA, CEDULA_CLIENTE,SUSER_NAME(), HOST_NAME(), GETDATE(), 'UD'
	FROM DELETED
END
GO

-- TRIGGERS PARA LA BITACORA AUTO

-- TRIGGER INSERT

DROP TRIGGER IF EXISTS TRG_AUTO_I
GO

CREATE TRIGGER TRG_AUTO_I
	ON dbo.[AUTO]
	AFTER INSERT
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[AUTO_BIT](NUMPLACA, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT NUMPLACA ,SUSER_NAME(), HOST_NAME(), GETDATE(), 'I'
	FROM INSERTED
END
GO

-- TRIGGER DELETE

DROP TRIGGER IF EXISTS TRG_AUTO_D
GO

CREATE TRIGGER TRG_AUTO_D
	ON dbo.[AUTO]
	AFTER DELETE
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[AUTO_BIT](NUMPLACA, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT NUMPLACA ,SUSER_NAME(), HOST_NAME(), GETDATE(), 'D'
	FROM DELETED
END
GO

-- TRIGGER UPDATE

DROP TRIGGER IF EXISTS TRG_AUTO_U
GO

CREATE TRIGGER TRG_AUTO_U
	ON dbo.[AUTO]
	AFTER UPDATE
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[AUTO_BIT](NUMPLACA, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT NUMPLACA ,SUSER_NAME(), HOST_NAME(), GETDATE(), 'UI'
	FROM INSERTED

	INSERT INTO dbo.[AUTO_BIT](NUMPLACA, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT NUMPLACA ,SUSER_NAME(), HOST_NAME(), GETDATE(), 'UD'
	FROM DELETED
END
GO

-- TRIGGERS PARA LA BITACORA CLIENTE

-- TRIGGER INSERT

DROP TRIGGER IF EXISTS TRG_CLIENTE_I
GO

CREATE TRIGGER TRG_CLIENTE_I
	ON dbo.[CLIENTE]
	AFTER INSERT
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[CLIENTE_BIT](CEDULA, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT CEDULA ,SUSER_NAME(), HOST_NAME(), GETDATE(), 'I'
	FROM INSERTED
END
GO

-- TRIGGER DELETE

DROP TRIGGER IF EXISTS TRG_CLIENTE_D
GO

CREATE TRIGGER TRG_CLIENTE_D
	ON dbo.[CLIENTE]
	AFTER DELETE
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[CLIENTE_BIT](CEDULA, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT CEDULA, SUSER_NAME(), HOST_NAME(), GETDATE(), 'D'
	FROM DELETED
END
GO

-- TRIGGER UPDATE

DROP TRIGGER IF EXISTS TRG_CLIENTE_U
GO

CREATE TRIGGER TRG_CLIENTE_U
	ON dbo.[CLIENTE]
	AFTER UPDATE
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[CLIENTE_BIT](CEDULA, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT CEDULA, SUSER_NAME(), HOST_NAME(), GETDATE(), 'UI'
	FROM INSERTED

	INSERT INTO dbo.[CLIENTE_BIT](CEDULA, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT CEDULA, SUSER_NAME(), HOST_NAME(), GETDATE(), 'UD'
	FROM DELETED
END
GO

-- TRIGGERS PARA LA BITACORA DISTRIBUIDOR

-- TRIGGER INSERT

DROP TRIGGER IF EXISTS TRG_DISTRIBUIDOR_I
GO

CREATE TRIGGER TRG_DISTRIBUIDOR_I
	ON dbo.[DISTRIBUIDOR]
	AFTER INSERT
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[DISTRIBUIDOR_BIT](ID, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT ID ,SUSER_NAME(), HOST_NAME(), GETDATE(), 'I'
	FROM INSERTED
END
GO

-- TRIGGER DELETE

DROP TRIGGER IF EXISTS TRG_DISTRIBUIDOR_D
GO

CREATE TRIGGER TRG_DISTRIBUIDOR_D
	ON dbo.[DISTRIBUIDOR]
	AFTER DELETE
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[DISTRIBUIDOR_BIT](ID, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT ID ,SUSER_NAME(), HOST_NAME(), GETDATE(), 'D'
	FROM DELETED
END
GO

-- TRIGGER UPDATE

DROP TRIGGER IF EXISTS TRG_DISTRIBUIDOR_U
GO

CREATE TRIGGER TRG_DISTRIBUIDOR_U
	ON dbo.[DISTRIBUIDOR]
	AFTER UPDATE
AS 
BEGIN
SET NOCOUNT ON;

	INSERT INTO dbo.[DISTRIBUIDOR_BIT](ID, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT ID, SUSER_NAME(), HOST_NAME(), GETDATE(), 'UI'
	FROM INSERTED

	INSERT INTO dbo.[DISTRIBUIDOR_BIT](ID, EXE_USER, EXE_MAQUINA, EXE_DATE, EXE_ACCION)
	SELECT ID, SUSER_NAME(), HOST_NAME(), GETDATE(), 'UD'
	FROM DELETED
END
GO

-- PRUEBA DE EJECUCION

USE ALQUILER_AUTOS;

EXEC INSERTAR_DISTRINUIDOR
	@ID = 1, @NOMBRE = 'JUAN', @DIRECCION = NULL, @CIUDAD = NULL, @TELEFONO = NULL, @EMAIL = NULL
GO

EXEC SELECCIONAR_DISTRIBUIDOR 
	@ID = 1
GO

EXEC ELIMINAR_DISTRIBUIDOR
	@ID = 1
GO

EXEC ACTUALIZAR_DISTRIBUIDOR
	@ID = 1, @NOMBRE = 'LEXUS', @DIRECCION = NULL, @CIUDAD = NULL, @TELEFONO = '666666', @EMAIL = NULL
GO

SELECT * FROM DISTRIBUIDOR_BIT

DELETE FROM DISTRIBUIDOR_BIT
WHERE ID = 1