CREATE DATABASE ALQUILER_AUTOS;

USE ALQUILER_AUTOS;

CREATE TABLE DISTRIBUIDOR (
	ID INT PRIMARY KEY,
	NOMBRE NCHAR(100),
	DIRECCION NCHAR(250),
	CIUDAD NCHAR(100),
	TELEFONO NCHAR(20) UNIQUE,
	EMAIL NCHAR(250) UNIQUE
)

CREATE TABLE AUTO (
	NUMPLACA NCHAR(6) PRIMARY KEY,
	MARCA NCHAR(100),
	DISTRIBUIDOR INT FOREIGN KEY REFERENCES DISTRIBUIDOR(ID),
	TIPO_MOTOR NCHAR(100), 
	TIPO_VEHICULO NCHAR(100),
	CAR_YEAR INT,
	PRECIO_ALQUILER DECIMAL(3,2)
)

CREATE TABLE CLIENTE(
	CEDULA NCHAR(12) PRIMARY KEY,
	NOMBRE NCHAR(100) NOT NULL,
	APELLIDO NCHAR(100) NOT NULL,
	DIRECCION NCHAR(250) NOT NULL,
	TELEFONO NCHAR(20) UNIQUE NOT NULL,
	LICENCIA NCHAR(20) UNIQUE NOT NULL
)

CREATE TABLE ALQUILER (
	MATRICULA NCHAR(6),
	CEDULA_CLIENTE NCHAR(12),
	FECHA_SAlIDA DATE NOT NULL,
	FECHA_ENTRADA DATE NOT NULL,
	FOREIGN KEY (MATRICULA) REFERENCES AUTO(NUMPLACA),
	FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE(CEDULA),
	PRIMARY KEY (MATRICULA, CEDULA_CLIENTE)
)
