-- VER LOS DATOS DE AUTOS EN ALQUILER
USE DB_DELTA

SELECT MATRICULA, CEDULA_CLIENTE, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER FROM ALQUILER

-- VER LA INFORMACION DE LOS ALQUILERES CUYO PRECIO ALQUILER POR DIA EXCEDA $75.00

SELECT NUMPLACA, MARCA, ID_DISTRIBUIDOR, TIPO_MOTOR, TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER FROM dbo.[AUTO]
WHERE PRECIO_ALQUILER > 75.00

-- REALIZA UNA CONSULTA QUE INDIQUE LAS VECES QUE HA SIDO ALQUILADO CADA AUTO

SELECT MATRICULA,
	   COUNT(MATRICULA) AS 'CANTIDAD DE VECES ALQUILADO'
FROM ALQUILER
GROUP BY MATRICULA

-- LISTADO DE AUTOS QUE HAN SIDO ALQUILADO POR MAS DE 4 DIAS

SELECT MATRICULA,
	   DATEDIFF(DAY, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER) AS 'DIAS ALQUILADO'
FROM ALQUILER
WHERE DATEDIFF(DAY, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER) > 4

-- LISTADO DE AUTOS POR DISTRIBUIDOR

-- LISTADO COMPLETO DE AUTO DE CADA DISTRIBUIDOR
SELECT D.NOMBRE AS 'DISTRIBUIDOR', A.NUMPLACA, A.MARCA, A.TIPO_MOTOR, 
TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER FROM AUTO A JOIN DISTRIBUIDOR D ON A.ID_DISTRIBUIDOR = D.ID
ORDER BY  D.NOMBRE

-- LISTADO DE AUTOS POR DISTRIBUIDOR

SELECT D.NOMBRE AS 'DISTRIBUIDOR', A.NUMPLACA, A.MARCA, A.TIPO_MOTOR, 
TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER FROM AUTO A JOIN DISTRIBUIDOR D ON A.ID_DISTRIBUIDOR = D.ID
WHERE A.ID_DISTRIBUIDOR = 1
ORDER BY  D.NOMBRE

SELECT D.NOMBRE AS 'DISTRIBUIDOR', A.NUMPLACA, A.MARCA, A.TIPO_MOTOR, 
TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER FROM AUTO A JOIN DISTRIBUIDOR D ON A.ID_DISTRIBUIDOR = D.ID
WHERE A.ID_DISTRIBUIDOR = 2
ORDER BY  D.NOMBRE

SELECT D.NOMBRE AS 'DISTRIBUIDOR', A.NUMPLACA, A.MARCA, A.TIPO_MOTOR, 
TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER FROM AUTO A JOIN DISTRIBUIDOR D ON A.ID_DISTRIBUIDOR = D.ID
WHERE A.ID_DISTRIBUIDOR = 3
ORDER BY  D.NOMBRE

SELECT D.NOMBRE AS 'DISTRIBUIDOR', A.NUMPLACA, A.MARCA, A.TIPO_MOTOR, 
TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER FROM AUTO A JOIN DISTRIBUIDOR D ON A.ID_DISTRIBUIDOR = D.ID
WHERE A.ID_DISTRIBUIDOR = 4
ORDER BY  D.NOMBRE

SELECT D.NOMBRE AS 'DISTRIBUIDOR', A.NUMPLACA, A.MARCA, A.TIPO_MOTOR, 
TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER FROM AUTO A JOIN DISTRIBUIDOR D ON A.ID_DISTRIBUIDOR = D.ID
WHERE A.ID_DISTRIBUIDOR = 5
ORDER BY  D.NOMBRE
