-- VER LOS DATOS DE AUTOS EN ALQUILER

SELECT * FROM ALQUILER

-- VER LA INFORMACION DE LOS ALQUILERES CUYO PRECIO ALQUILER POR DIA EXCEDA $75.00

SELECT * FROM AUTO
WHERE PRECIO_ALQUILER > 75.00

-- REALIZA UNA CONSULTA QUE INDIQUE LAS VECES QUE HA SIDO ALQUILADO CADA AUTO

SELECT MATRICULA,
	   COUNT(MATRICULA) AS 'CANTIDAD DE VECES ALQUILADO'
FROM ALQUILER
GROUP BY MATRICULA

-- LISTADO DE AUTOS QUE HAN SIDO ALQUILADO POR MAS DE 4 DIAS

SELECT MATRICULA,
	   DATEDIFF(DAY, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER) AS 'DIAS ALQUILADO'
FROM ALQUILER
WHERE DATEDIFF(DAY, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER) > 4

-- LISTADO DE AUTOS POR DISTRIBUIDOR

SELECT * FROM AUTO
WHERE DISTRIBUIDOR = 1

SELECT * FROM AUTO
WHERE DISTRIBUIDOR = 2

SELECT * FROM AUTO
WHERE DISTRIBUIDOR = 3

SELECT * FROM AUTO
WHERE DISTRIBUIDOR = 4

SELECT * FROM AUTO
WHERE DISTRIBUIDOR = 5