-- Procedimientos almacenados de DISTRIBUIDOR
USE DB_DELTA
-- SELECT

DROP PROCEDURE IF EXISTS SELECCIONAR_DISTRIBUIDOR
GO 

CREATE PROCEDURE SELECCIONAR_DISTRIBUIDOR @ID INT
AS 
BEGIN 
	SELECT ID, NOMBRE, DIRECCION, CIUDAD, TELEFONO, EMAIL FROM dbo.[DISTRIBUIDOR]
	WHERE ID = @ID
END 
GO

-- INSERT 

DROP PROCEDURE IF EXISTS INSERTAR_DISTRIBUIDOR 
GO 

CREATE PROCEDURE INSERTAR_DISTRIBUIDOR @ID INT, @NOMBRE NCHAR(100), @DIRECCION NCHAR(250),
	@CIUDAD NCHAR(100), @TELEFONO NCHAR(25), @EMAIL NCHAR(250) 
AS
BEGIN 
	INSERT INTO dbo.[DISTRIBUIDOR] (ID,NOMBRE, DIRECCION, CIUDAD, TELEFONO, EMAIL)
	VALUES (@ID,@NOMBRE,@DIRECCION,@CIUDAD,@TELEFONO,@EMAIL)
END
GO

-- UPDATE 

DROP PROCEDURE IF EXISTS ACTUALIZAR_DISTRIBUIDOR
GO 

CREATE PROCEDURE ACTUALIZAR_DISTRIBUIDOR @ID INT, @NOMBRE NCHAR(100), @DIRECCION NCHAR(250),
	@CIUDAD NCHAR(100), @TELEFONO NCHAR(25), @EMAIL NCHAR(250)
AS 
BEGIN
	IF @CIUDAD IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET DIRECCION = @DIRECCION
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET CIUDAD = @CIUDAD
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @CIUDAD IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET TELEFONO = @TELEFONO
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @CIUDAD IS NULL AND @TELEFONO IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET EMAIL = @EMAIL
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @CIUDAD IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET NOMBRE = @NOMBRE
		WHERE ID = @ID
	ELSE 
		UPDATE dbo.[DISTRIBUIDOR]
		SET NOMBRE = @NOMBRE, DIRECCION = @DIRECCION, 
		CIUDAD = @CIUDAD, TELEFONO = @TELEFONO,EMAIL = @EMAIL
		WHERE ID = @ID
END
GO

-- DELETE 

DROP PROCEDURE IF EXISTS ELIMINAR_DISTRIBUIDOR 
GO

CREATE PROCEDURE ELIMINAR_DISTRIBUIDOR @ID INT
AS
BEGIN
	DELETE FROM dbo.[DISTRIBUIDOR]
	WHERE ID = @ID
END
GO

-- Procedimientos almacenados de AUTO

-- SELECT 

DROP PROCEDURE IF EXISTS SELECCIONAR_AUTO 
GO

CREATE PROCEDURE  SELECCIONAR_AUTO @NUMPLACA NCHAR(6)
AS 
BEGIN 
	SELECT NUMPLACA, MARCA, ID_DISTRIBUIDOR, TIPO_MOTOR, TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER FROM dbo.[AUTO]
	WHERE NUMPLACA = @NUMPLACA
END
GO

-- INSERT

DROP PROCEDURE IF EXISTS INSERTAR_AUTO
GO

CREATE PROCEDURE INSERTAR_AUTO @NUMPLACA NCHAR(6), @MARCA NCHAR(100), @DISTRIBUIDOR INT, 
	@TIPO_MOTOR NCHAR(100), @TIPO_VEHICULO NCHAR(100), @AUTO_ANIO INT, @PRECIO_ALQUILER DECIMAL(6,2)
AS
BEGIN
	INSERT INTO dbo.[AUTO](NUMPLACA, MARCA, ID_DISTRIBUIDOR , TIPO_MOTOR, 
	TIPO_VEHICULO, AUTO_ANIO, PRECIO_ALQUILER)
	VALUES (@NUMPLACA, @MARCA, @DISTRIBUIDOR , @TIPO_MOTOR, 
	@TIPO_VEHICULO, @AUTO_ANIO, @PRECIO_ALQUILER)
END
GO

-- UPDATE 

DROP PROCEDURE IF EXISTS ACTUALIZAR_AUTO
GO 

CREATE PROCEDURE ACTUALIZAR_AUTO @NUMPLACA NCHAR(6), @MARCA NCHAR(100), @DISTRIBUIDOR INT,
	@TIPO_MOTOR NCHAR(100), @TIPO_VEHICULO NCHAR(10), @AUTO_ANIO INT, @PRECIO_ALQUILER DECIMAL(6,2)
AS 
BEGIN
	IF @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL AND @AUTO_ANIO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET MARCA = @MARCA
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL AND @AUTO_ANIO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET ID_DISTRIBUIDOR = @DISTRIBUIDOR
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_VEHICULO IS NULL AND @AUTO_ANIO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET TIPO_MOTOR = @TIPO_MOTOR
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @AUTO_ANIO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET TIPO_VEHICULO = @TIPO_VEHICULO
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL
	AND @PRECIO_ALQUILER IS NULL
		UPDATE dbo.[AUTO]
		SET AUTO_ANIO = @AUTO_ANIO
		WHERE NUMPLACA = @NUMPLACA
	ELSE IF @MARCA IS NULL AND @DISTRIBUIDOR IS NULL AND @TIPO_MOTOR IS NULL AND @TIPO_VEHICULO IS NULL
	AND @AUTO_ANIO IS NULL
		UPDATE dbo.[AUTO]
		SET PRECIO_ALQUILER = @PRECIO_ALQUILER
		WHERE NUMPLACA = @NUMPLACA
	ELSE 
		UPDATE dbo.[AUTO]
		SET MARCA = @MARCA, ID_DISTRIBUIDOR = @DISTRIBUIDOR, TIPO_MOTOR = @TIPO_MOTOR, 
		TIPO_VEHICULO = @TIPO_VEHICULO, AUTO_ANIO = @AUTO_ANIO,PRECIO_ALQUILER = @PRECIO_ALQUILER
		WHERE NUMPLACA = @NUMPLACA
END
GO

-- DELETE 

DROP PROCEDURE IF EXISTS ELIMINAR_AUTO
GO 

CREATE PROCEDURE ELIMINAR_AUTO @NUMPLACA NCHAR(6)
AS 
BEGIN 
	DELETE FROM dbo.[AUTO]
	WHERE NUMPLACA = @NUMPLACA
END

-- Procedimientos de CLIENTE

-- SELECT 

DROP PROCEDURE IF EXISTS SELECCIONAR_CLIENTE
GO

CREATE PROCEDURE SELECCIONAR_CLIENTE @CEDULA NCHAR(12)
AS
BEGIN
	SELECT CEDULA, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, LICENCIA FROM dbo.[CLIENTE]
	WHERE CEDULA = @CEDULA
END

-- INSERT 

DROP PROCEDURE IF EXISTS INSERTAR_CLIENTE
GO

CREATE PROCEDURE INSERTAR_CLIENTE @CEDULA NCHAR(12), @NOMBRE NCHAR(100), @APELLIDO NCHAR(100),
	@DIRECCION NCHAR(250), @TELEFONO NCHAR(20), @EMAIL NCHAR(250), @LICENCIA NCHAR(20)
AS 
BEGIN
	INSERT INTO dbo.[CLIENTE](CEDULA, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, LICENCIA)
	VALUES(@CEDULA, @NOMBRE, @APELLIDO, @DIRECCION, @TELEFONO, @EMAIL, @LICENCIA)
END

-- UPDATE

DROP PROCEDURE IF EXISTS ACTUALIZAR_CLIENTE
GO

CREATE PROCEDURE ACTUALIZAR_CLIENTE @CEDULA NCHAR(12), @NOMBRE NCHAR(100), @APELLIDO NCHAR(100),
	@DIRECCION NCHAR(250), @TELEFONO NCHAR(20), @EMAIL NCHAR(250), @LICENCIA NCHAR(20)
AS 
BEGIN 
	IF @APELLIDO IS NULL AND @DIRECCION IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL AND 
	@LICENCIA IS NULL
	UPDATE dbo.[CLIENTE]
	SET NOMBRE = @NOMBRE
	WHERE CEDULA = @CEDULA
	ELSE IF @NOMBRE IS NULL AND @DIRECCION IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL AND 
	@LICENCIA IS NULL
	UPDATE dbo.[CLIENTE]
	SET APELLIDO = @APELLIDO
	WHERE CEDULA = @CEDULA
	ELSE IF @NOMBRE IS NULL AND @APELLIDO IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL AND 
	@LICENCIA IS NULL
	UPDATE dbo.[CLIENTE]
	SET DIRECCION = @DIRECCION
	WHERE CEDULA = @CEDULA
	ELSE IF @NOMBRE IS NULL AND @APELLIDO IS NULL AND @DIRECCION IS NULL AND @EMAIL IS NULL AND 
	@LICENCIA IS NULL
	UPDATE dbo.[CLIENTE]
	SET TELEFONO = @TELEFONO
	WHERE CEDULA = @CEDULA
	ELSE IF @NOMBRE IS NULL AND @APELLIDO IS NULL AND @DIRECCION IS NULL AND @TELEFONO IS NULL AND 
	@LICENCIA IS NULL
	UPDATE dbo.[CLIENTE]
	SET EMAIL = @EMAIL
	WHERE CEDULA = @CEDULA
	ELSE IF @NOMBRE IS NULL AND @APELLIDO IS NULL AND @DIRECCION IS NULL AND @TELEFONO IS NULL AND 
	@EMAIL IS NULL
	UPDATE dbo.[CLIENTE]
	SET LICENCIA = @LICENCIA
	WHERE CEDULA = @CEDULA
	ELSE
	UPDATE dbo.[CLIENTE]
	SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, DIRECCION = @DIRECCION, TELEFONO = @TELEFONO,
	EMAIL = @EMAIL, LICENCIA = @LICENCIA
	WHERE CEDULA = @CEDULA
END

-- DELETE 
DROP PROCEDURE IF EXISTS ELIMINAR_CLIENTE
GO

CREATE PROCEDURE ELIMINAR_CLIENTE @CEDULA NCHAR(12)
AS 
BEGIN
	DELETE FROM CLIENTE
	WHERE CEDULA = @CEDULA
END
GO

-- Procedimientos almacenados de ALQUILER

-- SELECT 
DROP PROCEDURE IF EXISTS SELECCIONAR_ALQUILER
GO

CREATE PROCEDURE SELECCIONAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12)
AS 
BEGIN
	IF @MATRICULA IS NOT NULL AND @CEDULA_CLIENTE IS NOT NULL
	SELECT MATRICULA, CEDULA_CLIENTE, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER FROM dbo.[ALQUILER]
	WHERE MATRICULA = @MATRICULA AND CEDULA_CLIENTE = @CEDULA_CLIENTE
	ELSE IF @MATRICULA IS NULL
	SELECT MATRICULA, CEDULA_CLIENTE, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER FROM dbo.[ALQUILER]
	WHERE CEDULA_CLIENTE = @CEDULA_CLIENTE
	ELSE
	SELECT MATRICULA, CEDULA_CLIENTE, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER FROM dbo.ALQUILER
	WHERE MATRICULA = @MATRICULA
END

-- INSERT

DROP PROCEDURE IF EXISTS INSERTAR_ALQUILER
GO

CREATE PROCEDURE INSERTAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12), @FECHA_INICIO_ALQUILER DATE,
	@FECHA_FINAL_ALQUILER DATE
AS 
BEGIN 
	INSERT INTO dbo.[ALQUILER](MATRICULA,CEDULA_CLIENTE,FECHA_INICIO_ALQUILER,FECHA_FINAL_ALQUILER)
	VALUES(@MATRICULA,@CEDULA_CLIENTE,@FECHA_INICIO_ALQUILER,@FECHA_FINAL_ALQUILER)
END

-- UPDATE

DROP PROCEDURE IF EXISTS ACTUALIZAR_ALQUILER
GO

CREATE PROCEDURE ACTUALIZAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12), @FECHA_INICIO_ALQUILER DATE,
	@FECHA_FINAL_ALQUILER DATE, @OPCION INT
AS 
BEGIN
	IF @FECHA_FINAL_ALQUILER IS NULL
	UPDATE dbo.[ALQUILER]
	SET FECHA_INICIO_ALQUILER = @FECHA_INICIO_ALQUILER
	WHERE CEDULA_CLIENTE = @CEDULA_CLIENTE AND MATRICULA = @MATRICULA
	ELSE 
	UPDATE dbo.[ALQUILER]
	SET FECHA_FINAL_ALQUILER = @FECHA_FINAL_ALQUILER
	WHERE CEDULA_CLIENTE = @CEDULA_CLIENTE AND MATRICULA = @MATRICULA
END

-- DELETE 

DROP PROCEDURE IF EXISTS ELIMINAR_ALQUILER
GO

CREATE PROCEDURE ELIMINAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12)
AS
BEGIN
	DELETE FROM dbo.ALQUILER
	WHERE MATRICULA = @MATRICULA AND CEDULA_CLIENTE = @CEDULA_CLIENTE
END
GO