use master 

if exists( select 1 from sys.syslogins l where l.name = 'DeltaGroup' )
begin
	drop login DeltaGroup
end


CREATE LOGIN DeltaGroup WITH PASSWORD=N'MicroScopitos', DEFAULT_DATABASE=DB_DELTA


DROP DATABASE IF EXISTS DB_DELTA

CREATE DATABASE DB_DELTA;

USE DB_DELTA;

CREATE USER Binchilin FOR LOGIN DeltaGroup WITH DEFAULT_SCHEMA=[dbo]

ALTER ROLE [db_owner] ADD MEMBER Binchilin


CREATE MASTER KEY ENCRYPTION BY 
PASSWORD = '1dnjd#jwicoif$kfwpdqm168dq&dwqd7$$acacjaccunm%c9nmy63bbtr1vvv897/#f'


CREATE SYMMETRIC KEY lallave
WITH 
ALGORITHM = AES_256
ENCRYPTION BY 
PASSWORD = '%La/Mama/Es/La/Mama/De/Las/Mamases/Mundiales%'


CREATE TABLE DISTRIBUIDOR (
	ID INT PRIMARY KEY,
	NOMBRE NCHAR(100) NOT NULL,
	DIRECCION NCHAR(250),
	CIUDAD NCHAR(100),
	TELEFONO NCHAR(20) UNIQUE,
	EMAIL NCHAR(250) UNIQUE
)

CREATE TABLE AUTO (
	NUMPLACA NCHAR(6) PRIMARY KEY,
	MARCA NCHAR(100),
	ID_DISTRIBUIDOR INT FOREIGN KEY REFERENCES DISTRIBUIDOR(ID),
	TIPO_MOTOR NCHAR(100), 
	TIPO_VEHICULO NCHAR(100),
	AUTO_ANIO INT,
	PRECIO_ALQUILER DECIMAL(6,2)
)

ALTER TABLE AUTO ADD CONSTRAINT ID_DISTRIBUIDOR FOREIGN KEY (ID_DISTRIBUIDOR) REFERENCES DISTRIBUIDOR (ID)  ON DELETE CASCADE

CREATE TABLE CLIENTE(
	CEDULA NCHAR(12) PRIMARY KEY,
	NOMBRE NCHAR(100) NOT NULL,
	APELLIDO NCHAR(100) NOT NULL,
	DIRECCION NCHAR(250) NOT NULL,
	TELEFONO NCHAR(20) UNIQUE NOT NULL,
	EMAIL NCHAR(250) UNIQUE,
	LICENCIA NCHAR(20) UNIQUE NOT NULL,
	CONTRA VARBINARY(100) NOT NULL
)


CREATE TABLE ALQUILER (
	MATRICULA NCHAR(6),
	CEDULA_CLIENTE NCHAR(12),
	FECHA_INICIO_ALQUILER DATE NOT NULL,
	FECHA_FINAL_ALQUILER DATE NOT NULL,
	FOREIGN KEY (MATRICULA) REFERENCES AUTO(NUMPLACA),
	FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE(CEDULA),
	PRIMARY KEY (MATRICULA,CEDULA_CLIENTE)
)
ALTER TABLE ALQUILER ADD CONSTRAINT MATRICULA FOREIGN KEY (MATRICULA) REFERENCES AUTO (NUMPLACA)  ON DELETE CASCADE
ALTER TABLE ALQUILER ADD CONSTRAINT CEDULA_CLIENTE FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE (CEDULA)  ON DELETE CASCADE


