-- Procedimientos almacenados de DISTRIBUIDOR
USE DB_DELTA

-- SELECT

DROP PROCEDURE IF EXISTS SELECCIONAR_DISTRIBUIDOR
GO 

CREATE PROCEDURE SELECCIONAR_DISTRIBUIDOR @ID INT
AS 
BEGIN 
	SELECT ID, NOMBRE, DIRECCION, CIUDAD, TELEFONO, EMAIL FROM dbo.[DISTRIBUIDOR]
	WHERE ID = @ID
END 
GO

-- INSERT 

DROP PROCEDURE IF EXISTS INSERTAR_DISTRIBUIDOR 
GO 

CREATE PROCEDURE INSERTAR_DISTRIBUIDOR @ID INT, @NOMBRE NCHAR(100), @DIRECCION NCHAR(250),
	@CIUDAD NCHAR(100), @TELEFONO NCHAR(25), @EMAIL NCHAR(250) 
AS
BEGIN 
	INSERT INTO dbo.[DISTRIBUIDOR] (ID,NOMBRE, DIRECCION, CIUDAD, TELEFONO, EMAIL)
	VALUES (@ID,@NOMBRE,@DIRECCION,@CIUDAD,@TELEFONO,@EMAIL)
END
GO

-- UPDATE 

DROP PROCEDURE IF EXISTS ACTUALIZAR_DISTRIBUIDOR
GO 

CREATE PROCEDURE ACTUALIZAR_DISTRIBUIDOR @ID INT, @NOMBRE NCHAR(100), @DIRECCION NCHAR(250),
	@CIUDAD NCHAR(100), @TELEFONO NCHAR(25), @EMAIL NCHAR(250)
AS 
BEGIN
	IF @CIUDAD IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET DIRECCION = @DIRECCION
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET CIUDAD = @CIUDAD
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @CIUDAD IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET TELEFONO = @TELEFONO
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @CIUDAD IS NULL AND @TELEFONO IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET EMAIL = @EMAIL
		WHERE ID = @ID
	ELSE IF @DIRECCION IS NULL AND @CIUDAD IS NULL AND @TELEFONO IS NULL AND @EMAIL IS NULL
		UPDATE dbo.[DISTRIBUIDOR]
		SET NOMBRE = @NOMBRE
		WHERE ID = @ID
	ELSE 
		UPDATE dbo.[DISTRIBUIDOR]
		SET NOMBRE = @NOMBRE, DIRECCION = @DIRECCION, 
		CIUDAD = @CIUDAD, TELEFONO = @TELEFONO,EMAIL = @EMAIL
		WHERE ID = @ID
END
GO

-- DELETE 

DROP PROCEDURE IF EXISTS ELIMINAR_DISTRIBUIDOR 
GO

CREATE PROCEDURE ELIMINAR_DISTRIBUIDOR @ID INT
AS
BEGIN
	DELETE FROM dbo.[DISTRIBUIDOR]
	WHERE ID = @ID
END
GO






