-- Procedimientos almacenados de ALQUILER

-- SELECT 
DROP PROCEDURE IF EXISTS SELECCIONAR_ALQUILER
GO

CREATE PROCEDURE SELECCIONAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12)
AS 
BEGIN
	IF @MATRICULA IS NOT NULL AND @CEDULA_CLIENTE IS NOT NULL
	SELECT MATRICULA, CEDULA_CLIENTE, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER FROM dbo.[ALQUILER]
	WHERE MATRICULA = @MATRICULA AND CEDULA_CLIENTE = @CEDULA_CLIENTE
	ELSE IF @MATRICULA IS NULL
	SELECT MATRICULA, CEDULA_CLIENTE, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER FROM dbo.[ALQUILER]
	WHERE CEDULA_CLIENTE = @CEDULA_CLIENTE
	ELSE
	SELECT MATRICULA, CEDULA_CLIENTE, FECHA_INICIO_ALQUILER, FECHA_FINAL_ALQUILER FROM dbo.ALQUILER
	WHERE MATRICULA = @MATRICULA
END

-- INSERT

DROP PROCEDURE IF EXISTS INSERTAR_ALQUILER
GO

CREATE PROCEDURE INSERTAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12), @FECHA_INICIO_ALQUILER DATE,
	@FECHA_FINAL_ALQUILER DATE
AS 
BEGIN 
	INSERT INTO dbo.[ALQUILER](MATRICULA,CEDULA_CLIENTE,FECHA_INICIO_ALQUILER,FECHA_FINAL_ALQUILER)
	VALUES(@MATRICULA,@CEDULA_CLIENTE,@FECHA_INICIO_ALQUILER,@FECHA_FINAL_ALQUILER)
END

-- UPDATE

DROP PROCEDURE IF EXISTS ACTUALIZAR_ALQUILER
GO

CREATE PROCEDURE ACTUALIZAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12), @FECHA_INICIO_ALQUILER DATE,
	@FECHA_FINAL_ALQUILER DATE, @OPCION INT
AS 
BEGIN
	IF @FECHA_FINAL_ALQUILER IS NULL
	UPDATE dbo.[ALQUILER]
	SET FECHA_INICIO_ALQUILER = @FECHA_INICIO_ALQUILER
	WHERE CEDULA_CLIENTE = @CEDULA_CLIENTE AND MATRICULA = @MATRICULA
	ELSE 
	UPDATE dbo.[ALQUILER]
	SET FECHA_FINAL_ALQUILER = @FECHA_FINAL_ALQUILER
	WHERE CEDULA_CLIENTE = @CEDULA_CLIENTE AND MATRICULA = @MATRICULA
END

-- DELETE 

DROP PROCEDURE IF EXISTS ELIMINAR_ALQUILER
GO

CREATE PROCEDURE ELIMINAR_ALQUILER @MATRICULA NCHAR(6), @CEDULA_CLIENTE NCHAR(12)
AS
BEGIN
	DELETE FROM dbo.ALQUILER
	WHERE MATRICULA = @MATRICULA AND CEDULA_CLIENTE = @CEDULA_CLIENTE
END
GO